### ISSUE TITLE
How to setup an ARK: Survival Ascended server

### ISSUE THREAD

**Issue by frank-zap** [zaphosting/docs#1109]
### What topic does your proposed suggestion relate to?

ARK Survival Ascended kommt denmächst raus, ist aber Nitrado-exklusiv für mindestens 3 Jahre:
https://www.reddit.com/r/ARK/comments/15sbcqi/wildcard_announces_deal_giving_nitrado_a_monopoly/

Da sollte es sinnvoll sein, analog zu unserem Produkt vServer für Landwirtschafts-Simulator ein entsprechendes Produkt für ASA und dazu passend eine DOC zu erstellen, wie man einen ASA-Server aufsetzt.
Aktuell gibt es dazu natürlich noch keine Informationen; die letzte Information zum Release war Oktober 2023.

### How do you aim to structure your proposed change?

Ähnlicher Aufbau wie die Doc zu Farming Simulator dürfte sinnvoll sein.

### Could you briefly summarise the contents you plan to write about to ensure you have the appropriate technical knowledge?

Das sollte jemand machen, der sich besser mit Server Setup auskennt. :D

### What is your ZAP ID?

zap123456

### What is your Discord ID?

frankzap

### By submitting this form, you agree that...

- [X] You have read and understood our contribution section on our documentation.
- [X] You understand our guidelines and conditions that exist.
- [X] Your suggestion is original and not a duplicate.
- [X] You have provided the correct ZAP ID.
- [X] You have answered this suggestion form to the best of your ability.
- [X] You agree to receive feedback and communicate with our ZAP docs team.
- [X] You agree to the ZAP-Hosting Contribution Program Terms & Conditions, which can be [accessed here](https://zap-hosting.com/guides/docs/contribution-terms).

**Comment by ThatGuyJacobee** [comment]
That sounds like a great idea considering the circumstances with the exclusivity. I've added it to our to-do's list for new documentation guides. 👍

**Comment by NIREKI** [comment]
With Ark SA now released, it would be actually possible to create a documentation for setting up a server (Would this even be legal for you with the contract between Snail Games and Nitrado?).

It seems like it's currently only officially supported on Windows Server and not on Linux systems, but it is definitly possible to wine or proton (have it running myself). It's also possible to create a linux based Docker image with the gameserver running.

Is this still a documentation you are looking into and if yes - what parts should be part of it? (only windows or with linux+proton)

**Comment by ThatGuyJacobee** [comment]
Hey there, we have a guide already pending for this regarding setting up the ARK:SA dedicated server for our Windows vServers so there is no need for this anymore. Regardless, thank you for your interest!

**Comment by NIREKI** [comment]
Alright, thanks for your answer! Maybe in the future that guide can be expanded with some information about setting up the linux part and we can get back together.
