### ISSUE TITLE
Adding a specific Docs page for OS setup and troubleshooting 

### ISSUE THREAD

**Issue by SaikoArtFinn** [zaphosting/docs#1114]
### What topic does your proposed suggestion relate to?

Currently there are some OS specific setup Instructions within the root-server and Dedicated Server page. These can be very inconvenient as if you buy or rent one of the two, you might only look in the docs for that one specific Type of Server. a more convenient and easier to recognize way of preventing this, would be to create a specific tab where the different OS will be documented (i.e. Setup, Setup of additional IP addresses, SSH, maybe FTP, and some known issues or basic troubleshooting guides) 

### How do you aim to structure your proposed change?

```
- Setup OS & Troubleshooting for Root-, V- and Dedicated Servers
     - Debian
          - Setup
          - Adding IP addresses 
          - Enable SSH
          - Creating RDP connection
          - Known Issues 
     - Ubuntu
          - …
     - Windows
          - …
     -  …
```

### Could you briefly summarise the contents you plan to write about to ensure you have the appropriate technical knowledge?

this is just a suggestion on how to make this part easier and clearer to recognize for customers, i neither have the time nor writing skills to issue a pull request myself 

### What is your ZAP ID?

zap494149

### What is your Discord ID?

342742224326361089

### By submitting this form, you agree that...

- [X] You have read and understood our contribution section on our documentation.
- [X] You understand our guidelines and conditions that exist.
- [X] Your suggestion is original and not a duplicate.
- [X] You have provided the correct ZAP ID.
- [X] You have answered this suggestion form to the best of your ability.
- [X] You agree to receive feedback and communicate with our ZAP docs team.
- [X] You agree to the ZAP-Hosting Contribution Program Terms & Conditions, which can be [accessed here](https://zap-hosting.com/guides/docs/contribution-terms).

**Comment by ThatGuyJacobee** [comment]
Hey, thanks for creating this issue!

I understand that you do not want to work on this which is no problem. Thank you for the suggestion we will take it under consideration when improving content in the near future. 🙂

Many thanks!

**Comment by ThatGuyJacobee** [comment]
We have also added a new [issue template](https://github.com/zaphosting/docs/issues/new/choose) for general feedback and suggestions which you can use next time to provide us with details (since this is outside the scope of the Contribution program). 👍
