### ISSUE TITLE
ETS 2 - Dashboard

### ISSUE THREAD

**Issue by itscc8** [zaphosting/docs#1120]
### What topic does your proposed suggestion relate to?

I'd like to write a page about ETS 2 showing the dashboard after ordering the server (similar to [CS 2](https://zap-hosting.com/guides/docs/cs2-firststeps-dashboard))

### How do you aim to structure your proposed change?

Same as the above mentioned example. I will go through each of the categories of the dashboard and describe it in detail with screenshots.

### Could you briefly summarise the contents you plan to write about to ensure you have the appropriate technical knowledge?

Not much technical knowledge needed here :)

### What is your ZAP ID?

zap473905

### What is your Discord ID?

501132017367384070

### Do you have any previous experience in writing and publishing articles?

Yeah I do. Wrote some articles for zap's docs page :0

### Additional Information

-

### Do you depend on a service for creating your guide?

-

### By submitting this form, you agree that...

- [X] You have read and understood our contribution section on our documentation.
- [X] You understand our guidelines and conditions that exist.
- [X] Your suggestion is original and not a duplicate.
- [X] You have provided the correct ZAP ID.
- [X] You have answered this suggestion form to the best of your ability.
- [X] You agree to receive feedback and communicate with our ZAP docs team.
- [X] You agree to the ZAP-Hosting Contribution Program Terms & Conditions, which can be [accessed here](https://zap-hosting.com/guides/docs/contribution-terms).

**Comment by ThatGuyJacobee** [comment]
Hey again!

As far as I know, these First Steps>Dashboard guides are reused across most of the games, thus it doesn't necessarily require a new page. We will consider this as a suggestion and will reuse our existing dashboard page and place it into the Truck Sim subsection so thanks for pointing this out!

Many thanks 🙂
