### ISSUE TITLE
ETS 2 - Connect to server

### ISSUE THREAD

**Issue by itscc8** [zaphosting/docs#1121]
### What topic does your proposed suggestion relate to?

I'd like to write a page about ETS 2 showing how to connect to a server (similar to [CS 2](https://zap-hosting.com/guides/docs/cs2-firststeps-connect))

### How do you aim to structure your proposed change?

Same as the above mentioned example. 
I'll install the game on my pc and screenshot every step and also write instructions. 

### Could you briefly summarise the contents you plan to write about to ensure you have the appropriate technical knowledge?

Not much technical knowledge needed here either :)

### What is your ZAP ID?

zap473905

### What is your Discord ID?

501132017367384070

### Do you have any previous experience in writing and publishing articles?

Yeah I do. Wrote some articles for zap's docs page :0

### Additional Information

-

### Do you depend on a service for creating your guide?

-

### By submitting this form, you agree that...

- [X] You have read and understood our contribution section on our documentation.
- [X] You understand our guidelines and conditions that exist.
- [X] Your suggestion is original and not a duplicate.
- [X] You have provided the correct ZAP ID.
- [X] You have answered this suggestion form to the best of your ability.
- [X] You agree to receive feedback and communicate with our ZAP docs team.
- [X] You agree to the ZAP-Hosting Contribution Program Terms & Conditions, which can be [accessed here](https://zap-hosting.com/guides/docs/contribution-terms).

**Comment by ThatGuyJacobee** [comment]
Hi there.

This also sounds like a nice addition as it is missing in the Gameserver->Truck Sim section. Feel free to go ahead with this and submit a PR once you are ready. 👍

Kind regards and many thanks! 🙂
