### ISSUE TITLE
The Front Basic Pages

### ISSUE THREAD

**Issue by itscc8** [zaphosting/docs#1127]
### What topic does your proposed suggestion relate to?

I'd like to write some of the basic "starter" pages for the new game The Front:
- First Time Server Setup (including configuration)
- How to connect to servers

### How do you aim to structure your proposed change?

Similar to [Minecraft's connect page](https://zap-hosting.com/guides/docs/minecraft-firststeps-connect) and [FiveM's dashboard page](https://zap-hosting.com/guides/docs/fivem-dashboard).

### Could you briefly summarise the contents you plan to write about to ensure you have the appropriate technical knowledge?

I'll write about joining a server via ip or name and changing the server's password name and other config options.

### What is your ZAP ID?

zap473905

### What is your Discord ID?

501132017367384070

### Do you have any previous experience in writing and publishing articles?

Yeah I do. Wrote some articles for zap's docs page :0

### Additional Information

 It's a new game and there aren't many guides out there so I might write a few more guides about it if I have time.
Edit: I might be blind but is there a category for this game or would I need to make it myself? That wouldn't be a problem though I thought I should ask :)

### Do you depend on a service for creating your guide?

If you guys could provide me with a server for the game it will help a lot.

### By submitting this form, you agree that...

- [X] You have read and understood our contribution section on our documentation.
- [X] You understand our guidelines and conditions that exist.
- [X] Your suggestion is original and not a duplicate.
- [X] You have provided the correct ZAP ID.
- [X] You have answered this suggestion form to the best of your ability.
- [X] You agree to receive feedback and communicate with our ZAP docs team.
- [X] You agree to the ZAP-Hosting Contribution Program Terms & Conditions, which can be [accessed here](https://zap-hosting.com/guides/docs/contribution-terms).

**Comment by ThatGuyJacobee** [comment]
Hey CC8,

The "dashboard" guide that we use is reusable, so it will be done by us and won't need to be written up again. Likewise, the "connect to server" guide is already in the process of being created.

I will be closing this issue however, if you have any idea other than these two guide ideas specifically, we are more than happy to hear it, simply drop us a new issue. 😁

Many thanks!
