### ISSUE TITLE
How to join server without VNC console | VPS

### ISSUE THREAD

**Issue by kamilhrajemin** [zaphosting/docs#1181]
### What topic does your proposed suggestion relate to?

How to join your VPS without VNC console

### How do you aim to structure your proposed change?

steps for joining VPS with remote deskopt connection

### Could you briefly summarise the contents you plan to write about to ensure you have the appropriate technical knowledge?

I plan to write about how to connect to a VPS server without a VNC console. In the case of OS Windows (your computer), we use Remote Deskopt Connection and IP server, we give connect. It will require the password you entered on Zap Hosting, now you can copy files etc without the need for AnyDesk.

### What is your ZAP ID?

zap1064465

### What is your Discord ID?

675315184763535370

### By submitting this form, you agree that...

- [X] You have read and understood our contribution section on our documentation.
- [X] You understand our guidelines and conditions that exist.
- [X] Your suggestion is original and not a duplicate.
- [X] You have provided the correct ZAP ID.
- [X] You have answered this suggestion form to the best of your ability.
- [X] You agree to receive feedback and communicate with our ZAP docs team.
- [X] You agree to the ZAP-Hosting Contribution Program Terms & Conditions, which can be [accessed here](https://zap-hosting.com/guides/docs/contribution-terms).

**Comment by Blumlaut** [comment]
Guide already exists:
https://zap-hosting.com/guides/docs/vserver-windows-userdp
https://zap-hosting.com/guides/docs/vserver-linux-ssh
