### ISSUE TITLE
Expansion of Docs for Project Zomboid Game server setup

### ISSUE THREAD

**Issue by MTLTSaul** [zaphosting/docs#1182]
### What topic does your proposed suggestion relate to?

Project Zomboid Game, Guide for dedicated Server Setup with steam mods. 

### How do you aim to structure your proposed change?

1. Information collection.
2. Imagery collection and editing.
3. Full Draft document creation.
4. Getting your review and further instructions.

### Could you briefly summarise the contents you plan to write about to ensure you have the appropriate technical knowledge?

**Introduction** - Brief intro to Project Zomboid Multiplayer and key differences from Single Player mode.
**Steam Mods** - Manual for choosing mods and creating libraries that can be shared with friends that will be joining the game.
**Config Files** - Manual for correctly setting up ZAP.ini, ZAP_SandboxVars & ZAP_spawnregions+points files. Explaining key points.
**FTP & Backups** - Via FileZilla, visually describing what's what and where to put it or what to keep for backups. 
**Connecting to server** - Visual Explanation on how to find and to connect to server while in game and relation to 02 Panel Settings.
**Admin Login & Functions** - Briefly explaining how to login as admin. Description of role permissions & admin commands.
**ZAP Console** - Explaining basic functions to avoid using Admin Login. Also auto Backup & Restart recommendations.
**Troubleshooting** - Explaining most usual crash cases while checking logs and console on server panels and providing solutions.

_*Optional If ok Legally:_
**Community Content** - Links to community pages like interactive Maps (Official & Mod) and YouTube vids to guides and tutorials.  

### What is your ZAP ID?

SaulMT zap1151250

### What is your Discord ID?

Saul#5071

### Do you have any previous experience in writing and publishing articles?

Professionally had to write up Operational step by step manuals for various systems for staff members in various companies.

### By submitting this form, you agree that...

- [X] You have read and understood our contribution section on our documentation.
- [X] You understand our guidelines and conditions that exist.
- [X] Your suggestion is original and not a duplicate.
- [X] You have provided the correct ZAP ID.
- [X] You have answered this suggestion form to the best of your ability.
- [X] You agree to receive feedback and communicate with our ZAP docs team.
- [X] You agree to the ZAP-Hosting Contribution Program Terms & Conditions, which can be [accessed here](https://zap-hosting.com/guides/docs/contribution-terms).

**Comment by ThatGuyJacobee** [comment]
Hi there @MTLTSaul! Thank you for your interest in the Contribution Program! 👋

At the moment, we believe that Project Zomboid doesn't warrant the need for a dedicated server setup guide. Furthermore, there are many topics that you have suggested and it wouldn't make sense to place them into a single guide. There are also a few topics that generally don't require attention as we have general guides that cover them.

However, many of the points that you have mentioned in your content summary would fit well into the Project Zomboid section in our gameserver category.

I believe it would be best to split your suggestion ideas into a few separate guides within the `Gameserver->Project Zomboid` section on our docs, as follows:
- Install Mods / Community Content - Explore how to install mods with perhaps an example or two (you can link to "popular" mods too, shouldn't be an issue here).
- Server Configuration - Explain how to access config files and explore the server configuration parameters (use [this for reference](https://zap-hosting.com/guides/docs/enshrouded-configuration)).
- Manage Savegames - Explore how to backup savegames and how to upload and activate (use [this for reference](https://zap-hosting.com/guides/docs/enshrouded-server-savegames)).

We typically do 1 guide per suggestion, therefore let's assume this suggestion covers the "Install Mods / Community Content" guide which I believe is the most useful. Once you complete this guide and submit it, you could then submit further issue suggestions for other guides too. 👍

What do you think about this? Is this fine with you? If you have any questions, please let me know. 😀

Many thanks! 💚

**Comment by ThatGuyJacobee** [comment]
Heya, just to check up that everything is alright, are you still interested in this? @MTLTSaul 🙂
