### ISSUE TITLE
Register domain with cloudflare

### ISSUE THREAD

**Issue by Thetntteam** [zaphosting/docs#1224]
### What topic does your proposed suggestion relate to?

It relates to domains on zap hosting.

### How do you aim to structure your proposed change?

With ExpertDNS, you can seamlessly integrate your domain with Cloudflare's powerful DNS management services. This guide will walk you through linking your domain to Cloudflare for enhanced performance, security, and manageability.

Step 1: Accessing ExpertDNS Option

Navigate to the domain administration page of your domain’s web panel
Locate the ExpertDNS option. By default, EasyDNS is selected.
Check the "expertDNS Activate" option to enable ExpertDNS functionality.

Step 2: Setting Up Your Domain on Cloudflare

Log into your Cloudflare account.
Add your website and follow the setup steps provided.

Proceed to step 4 of the Cloudflare setup process, where it provides you with nameservers.

In the ExpertDNS area, delete the zap hosting nameservers and replace them with the provided ones from Cloudflare.

After entering Cloudflare's nameservers, save the changes by clicking on the "Save" button.

Step 4: Completing the Setup on Cloudflare

Finish the setup on cloudflare. Allow some time for Cloudflare to recognize your nameserver change.

Step 5: Confirming Integration
Verify that your domain is successfully integrated with Cloudflare by checking its status within your Cloudflare dashboard.

I have images ready for it aswell.

### Could you briefly summarise the contents you plan to write about to ensure you have the appropriate technical knowledge?

Nameservers are important parts of the Domain Name System (DNS) that convert human-readable domain names into IP addresses which are used by computers to communicate over the internet. Whenever a user enters a domain name into a web browser, it makes requests to nameservers in order to get the IP address of the website’s server. Cloudflare is a content delivery network (CDN) and DNS service provider that delivers improved website performance, security and reliability. By associating your domain with Cloudflare, you can take advantage of their global network infrastructure for faster content delivery, DDoS attack mitigation as well as efficient management of DNS settings. Domains act as unique identifiers for websites and are registered through domain registrars comprising two main parts; top-level domain (TLD), such as .com or .org, and second-level domain (SLD), which is a unique name chosen by the website owner. Managed via nameservers, DNS records determine how domain names are resolved to specific IP addresses thereby allowing different internet services like email routing or website hosting.

### What is your ZAP ID?

zap835229

### What is your Discord ID?

472216898520481825

### Additional Information

![image](https://github.com/zaphosting/docs/assets/54711505/490d073d-529b-431e-b5b7-7e711283f012) 
![image](https://github.com/zaphosting/docs/assets/54711505/b542e094-628a-45ac-b0ed-94847b17fc52)
![image](https://github.com/zaphosting/docs/assets/54711505/0045da70-9381-41f8-99cc-7fbf15247c41)
![image](https://github.com/zaphosting/docs/assets/54711505/fc8ac311-7241-4ea6-87fd-34f696850d3c)

### Do you depend on a service for creating your guide?

I have my own domain registered with Zap Hosting

### By submitting this form, you agree that...

- [X] You have read and understood our contribution section on our documentation.
- [X] You understand our guidelines and conditions that exist.
- [X] Your suggestion is original and not a duplicate.
- [X] You have provided the correct ZAP ID.
- [X] You have answered this suggestion form to the best of your ability.
- [X] You agree to receive feedback and communicate with our ZAP docs team.
- [X] You agree to the ZAP-Hosting Contribution Program Terms & Conditions, which can be [accessed here](https://zap-hosting.com/guides/docs/contribution-terms).

**Comment by ThatGuyJacobee** [comment]
Completed!
