### ISSUE TITLE
QBCore - Settings Permissions

### ISSUE THREAD

**Issue by ddainusshaa** [zaphosting/docs#1227]
### What topic does your proposed suggestion relate to?

I saw on the docs the Contribution Program and i were intrested in writing overall new things for Game Server QBCore Section. Because there is only about settings permissions. So if it would be updated people would understand more about the framework and how to work with it.

### How do you aim to structure your proposed change?

First section there would be explantion what is ace permissions Next Section how to set permissions with ace permissions on qbcore next section how to set qbcore permissions difrrent way and the 4th section how to implement the ace permissions by yourself so use it with qbcore command function.

### Could you briefly summarise the contents you plan to write about to ensure you have the appropriate technical knowledge?

How ace permissions work, how to get them working and how to implement them.

Setting permissions

### What is your ZAP ID?

zap1114784

### What is your Discord ID?

348008117004402688

### Do you have any previous experience in writing and publishing articles?

I have been intrested in FiveM Development since 2017 close to 2018 started working with default base. Then i after some years switched to qbus what now is qbcore. So basiclly working with qbcore since it was named qbus.

### Additional Information

This will be just the start. I will continue working on new sections for QBCore Category but as i hear i need to make new issue for that so this issue is for Setting Permissions.

### By submitting this form, you agree that...

- [X] You have read and understood our contribution section on our documentation.
- [X] You understand our guidelines and conditions that exist.
- [X] Your suggestion is original and not a duplicate.
- [X] You have provided the correct ZAP ID.
- [X] You have answered this suggestion form to the best of your ability.
- [X] You agree to receive feedback and communicate with our ZAP docs team.
- [X] You agree to the ZAP-Hosting Contribution Program Terms & Conditions, which can be [accessed here](https://zap-hosting.com/guides/docs/contribution-terms).

**Comment by ddainusshaa** [comment]
Hey, how much do i need to wait for review?

**Comment by ThatGuyJacobee** [comment]
Contribution declined due to plagiarism. Please take a look at the Pull Request for more information.
