### ISSUE TITLE
Migrating Your WordPress Site to Zap Hosting

### ISSUE THREAD

**Issue by TriggeredLegend** [zaphosting/docs#1305]
### What topic does your proposed suggestion relate to?

The proposed suggestion relates to **WordPress site migration and web hosting**. It involves transferring a WordPress website from one hosting provider to another (Zap Hosting), updating domain DNS settings, and securing the website with an SSL certificate. This topic encompasses aspects of website management, domain configuration, and hosting services.

### How do you aim to structure your proposed change?

The proposed change will be structured as a step-by-step guide to help users migrate their WordPress site to Zap Hosting. Here is the structure with headings and steps:

1. **Introduction**
   - Brief overview of the purpose of the guide
   - Benefits of migrating to Zap Hosting

2. **Prerequisites**
   - Requirements before starting the migration process
   - Admin access to domain hosting nameservers
   - Admin access to old WordPress hosting

3. **Step 1: Set up Your New WordPress Hosting on Zap Hosting**
   - Purchase a suitable webspace hosting plan from Zap Hosting
   - Link your domain to your new Zap Hosting webspace

4. **Step 2: Migrate Your WordPress Site**
   - **Access Your WordPress Admin Panel on Old Hosting**
     - How to log in to your WordPress admin panel
   - **Install Migrate Guru Plugin on Old Hosting**
     - Instructions to install and activate the Migrate Guru plugin
   - **Configure Migrate Guru Plugin**
     - Steps to configure the plugin for migration
   - **Install WordPress and Migrate Guru Plugin on Zap Hosting Webspace**
     - Install WordPress on the new Zap Hosting webspace
     - Install and activate Migrate Guru on Zap Hosting
   - **Get Your Migration Key**
     - Instructions to acquire the migration key
   - **Enter Your Migration Key and Proceed with the Migration Process**
     - How to enter the migration key and start the migration
   - **Complete the Migration Process**
     - Details on verifying the migration process

5. **Step 3: Update Your Domain's DNS Settings**
   - **Acquire the IP Address of the Zap Hosting Webspace**
     - How to find the new webspace IP address
   - **Update Your Domain's DNS Settings**
     - Instructions to update DNS settings to point to the new hosting

6. **Step 4: Secure Your Website with an SSL Certificate**
   - Instructions on enabling SSL on the new hosting setup

7. **Conclusion**
   - Final steps to check if the migration was successful
   - Encouragement to verify that the website is functioning correctly

8. **Additional Notes**
   - Information on DNS propagation time
   - Recommendation to back up your website before starting the migration

This structure ensures that users have a clear and concise roadmap to follow when migrating their WordPress site to Zap Hosting, with all necessary steps and precautions outlined.

### Could you briefly summarise the contents you plan to write about to ensure you have the appropriate technical knowledge?

Certainly! Here's a brief summary of the content planned for the guide on migrating a WordPress site to Zap Hosting:

- **Introduction**
  - Overview of the guide’s purpose: to assist users in migrating their WordPress website to Zap Hosting.
  - Benefits of choosing Zap Hosting: high-speed SSDs, full access control, live chat support, and flexible payment options.

- **Prerequisites**
  - Confirm necessary prerequisites are met before starting:
    - Admin access to current domain hosting nameservers.
    - Admin access to the old WordPress hosting provider.
  
- **Step 1: Set Up Your New WordPress Hosting on Zap Hosting**
  - Visit Zap Hosting’s webspace product page to purchase a suitable hosting plan.
  - Follow steps to link the domain to the new Zap Hosting webspace using DNS settings.

- **Step 2: Migrate Your WordPress Site**
  - **Access Your WordPress Admin Panel on Old Hosting**
    - Guide users to log in to the WordPress admin panel on their current host.
  - **Install and Configure Migrate Guru Plugin on Old Hosting**
    - Navigate to the Plugins section and install the "Migrate Guru" plugin.
    - Activate the plugin and configure it by entering the required details.
  - **Install WordPress and Migrate Guru Plugin on Zap Hosting Webspace**
    - Instructions for installing WordPress on the new Zap Hosting webspace.
    - Reinstall and activate the Migrate Guru plugin on the new webspace.
  - **Get Your Migration Key**
    - Guide on obtaining the migration key from the Migrate Guru plugin on Zap Hosting.
  - **Enter Your Migration Key and Proceed with the Migration Process**
    - Instructions to enter the migration key on the old host’s Migrate Guru plugin.
    - Steps to initiate and monitor the migration process.
  - **Complete the Migration Process**
    - Verification steps to ensure all data has been successfully migrated.

- **Step 3: Update Your Domain's DNS Settings**
  - **Acquire the IP Address of the Zap Hosting Webspace**
    - Guide to locate the new IP address in the Zap Hosting dashboard.
  - **Update Your Domain's DNS Settings**
    - Instructions for updating the DNS records to point to the new hosting IP.
    - Explanation of potential propagation time and steps to verify changes.

- **Step 4: Secure Your Website with an SSL Certificate**
  - Instructions to enable SSL on the new hosting environment.
  - Steps to verify SSL configuration through the Plesk panel or equivalent on Zap Hosting.

- **Conclusion**
  - Recap of the steps taken for a successful migration.
  - Encourage users to check the functionality of their website thoroughly after migration.

- **Additional Notes**
  - Mention of DNS propagation delay and its impact on website availability.
  - Emphasis on taking a complete backup before starting the migration process to avoid data loss.

This summary covers all the essential technical details needed to guide users through the process of migrating their WordPress site to Zap Hosting while ensuring all necessary precautions and steps are clearly outlined.

### What is your ZAP ID?

zap949708

### What is your Discord ID?

677921215557664799

### Do you have any previous experience in writing and publishing articles?

Yes, I have experience writing and publishing tutorial articles. I previously ran a blog about Valorant, where I posted guides and tips. The website is no longer available, but I gained experience in creating clear, step-by-step content.

### By submitting this form, you agree that...

- [X] You have read and understood our contribution section on our documentation.
- [X] You understand our guidelines and conditions that exist.
- [X] Your suggestion is original and not a duplicate.
- [X] You have provided the correct ZAP ID.
- [X] You have answered this suggestion form to the best of your ability.
- [X] You agree to receive feedback and communicate with our ZAP docs team.
- [X] You agree to the ZAP-Hosting Contribution Program Terms & Conditions, which can be [accessed here](https://zap-hosting.com/guides/docs/contribution-terms).

**Comment by ThatGuyJacobee** [comment]
Ready to be merged.
