### ISSUE TITLE
How to Install and Setup GitLab on Linux VPS

### ISSUE THREAD

**Issue by TriggeredLegend** [zaphosting/docs#1311]
### What topic does your proposed suggestion relate to?

- **Hosting and managing Git repositories on your server using GitLab**.

### How do you aim to structure your proposed change?

- Introduction
- Prerequisites
  - Hardware
  - Software
- Preparation
- Installation
- Manage GitLab
- Conclusion

### Could you briefly summarise the contents you plan to write about to ensure you have the appropriate technical knowledge?

- I plan to create a guide that starts with an introduction to GitLab and provides the prerequisites, including the minimum and recommended requirements for running GitLab. Then, I'll give some preparation instructions, followed by an installation guide. After that, I'll provide instructions for managing GitLab via a web browser, and finally, I'll conclude the guide.

### What is your ZAP ID?

zap949708

### What is your Discord ID?

677921215557664799

### Do you have any previous experience in writing and publishing articles?

- Yes, I have experience in writing and publishing tutorial articles. Previously, I ran a blog about Valorant where I posted guides and tips. The website is no longer available, but I gained experience in creating clear, step-by-step content.

- Also, I wrote the guide post #1307

### Do you depend on a service for creating your guide?

- Yes, I'll need a Linux VPS to host GitLab temporarily to assist with the guide.

### By submitting this form, you agree that...

- [X] You have read and understood our contribution section on our documentation.
- [X] You understand our guidelines and conditions that exist.
- [X] Your suggestion is original and not a duplicate.
- [X] You have provided the correct ZAP ID.
- [X] You have answered this suggestion form to the best of your ability.
- [X] You agree to receive feedback and communicate with our ZAP docs team.
- [X] You agree to the ZAP-Hosting Contribution Program Terms & Conditions, which can be [accessed here](https://zap-hosting.com/guides/docs/contribution-terms).

**Comment by ThatGuyJacobee** [comment]
Hey there @TriggeredLegend, thank you for your interest in the Contribution Program again! 💚

This sounds like a great idea, it would best fit under vRootserver -> Services -> Install GitLab. Your suggestion is accepted and you can begin writing the guide. Make sure to have a look at our [process and guidelines](https://zap-hosting.com/guides/docs/contribution-guides) guide pages for contributing, to ensure that your content is written to a high standard. 👍

If you have any questions or have a query, don't hesitate to drop a message here and we will be more than happy to help :)

**Comment by ThatGuyJacobee** [comment]
Hey there @TriggeredLegend,

I have added a Linux VPS to your account. It will be valid for 5 days from today, after which it will be removed. 👍

Many thanks and good luck with your content!

**Comment by ThatGuyJacobee** [comment]
Hey there! The complementary service that we provided was valid up until today. How is the progress looking for this guide? Are you near completion?

Many thanks.

**Comment by TriggeredLegend** [comment]
- Hey @ThatGuyJacobee, the writing is completed, and I've submitted a pull request - #1316.

**Comment by ThatGuyJacobee** [comment]
Perfect! Will be reviewed very shortly. ✌️

**Comment by ThatGuyJacobee** [comment]
Completed! 🚀
