### ISSUE TITLE
How To Create a Self-Signed SSL Certificate for Nginx in Ubuntu

### ISSUE THREAD

**Issue by TriggeredLegend** [zaphosting/docs#1361]
### What topic does your proposed suggestion relate to?

- The proposed suggestion relates to **Linux system administration**, specifically focusing on **SSL/TLS certificate management** and **web server configuration** with **Nginx** on **Ubuntu**. It involves creating a self-signed SSL certificate for secure HTTPS connections, a common task for securing websites and applications.

### 1. **Install OpenSSL (if not installed)**
   - Ensure OpenSSL is installed on your system.

### 2. **Create a Directory for the SSL Certificate**
   - Organize and store SSL certificates in a dedicated directory.

### 3. **Generate the Self-Signed SSL Certificate and Private Key**
   - Use OpenSSL to create the certificate and private key.
   - Enter the required details during the certificate generation process.

### 4. **Configure Nginx to Use the SSL Certificate**
   - Edit your Nginx site configuration to add SSL settings.
   - Ensure both HTTP to HTTPS redirection and SSL settings are included.

### 5. **Test Nginx Configuration**
   - Test the Nginx configuration for syntax errors before restarting.

### 6. **Restart Nginx**
   - Apply the changes by restarting the Nginx service.

### 7. **Verify SSL Certificate**
   - Use a browser to verify the SSL certificate and check for the security warning.
   - Optionally, verify via `curl` for command-line testing.

### Could you briefly summarise the contents you plan to write about to ensure you have the appropriate technical knowledge?

- **Understanding SSL/TLS**:
  - SSL (Secure Sockets Layer) and TLS (Transport Layer Security) protocols are used to secure communications over a network.
  - Self-signed certificates are not verified by a trusted certificate authority (CA) but can still be used for encryption in testing or internal environments.

- **Prerequisites**:
  - Ubuntu server with root or sudo privileges.
  - Nginx installed and running.
  - OpenSSL installed for generating SSL certificates.

- **Generating the SSL Certificate**:
  - `openssl req -x509` command used to create a self-signed certificate.
  - The process generates a public certificate (`.crt`) and a private key (`.key`).
  - Key information entered includes country, organization, common name (domain or IP), etc.

- **Nginx Configuration for SSL**:
  - Configuring Nginx to listen on port 443 for SSL traffic.
  - Specifying paths for the certificate (`.crt`) and private key (`.key`).
  - Enforcing HTTPS by redirecting HTTP (port 80) traffic to HTTPS.
  - SSL best practices for stronger security (e.g., TLS protocols, secure ciphers).

- **Testing and Verifying the Setup**:
  - Verifying Nginx configuration for syntax errors (`nginx -t`).
  - Restarting Nginx to apply changes.
  - Verifying SSL functionality via a web browser (noting that a self-signed certificate will trigger a warning).
  - Using `curl` to test HTTPS connectivity.

- **Security Considerations**:
  - Self-signed certificates are only appropriate for development, internal use, or testing.
  - In a production environment, certificates from a trusted CA should be used to avoid security warnings and ensure trust.

### What is your ZAP ID?

zap949708

### What is your Discord ID?

677921215557664799

### Do you have any previous experience in writing and publishing articles?

- Yes, I have experience in writing and publishing tutorial articles. Previously, I ran a blog about Valorant where I posted guides and tips. The website is no longer available, but I gained experience in creating clear, step-by-step content.

### Do you depend on a service for creating your guide?

- Yes, I'll need a Linux VPS to host SSL temporarily to assist with the guide.

### By submitting this form, you agree that...

- [X] You have read and understood our contribution section on our documentation.
- [X] You understand our guidelines and conditions that exist.
- [X] Your suggestion is original and not a duplicate.
- [X] You have provided the correct ZAP ID.
- [X] You have answered this suggestion form to the best of your ability.
- [X] You agree to receive feedback and communicate with our ZAP docs team.
- [X] You agree to the ZAP-Hosting Contribution Program Terms & Conditions, which can be [accessed here](https://zap-hosting.com/guides/docs/contribution-terms).

**Comment by ThatGuyJacobee** [comment]
Hi there,

Thanks for your interest in the Contribution Program. Unfortunately, we have decided to decline this suggestion because we already cover the process of setting up SSL certificates via [Certbot](https://zap-hosting.com/guides/docs/vserver-linux-certbot). Creating a self-signed certificate seems unnecessary for most people as realistically you would want one from a registered CA in most cases.

Kind regards!
